// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: pc28.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pc28_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pc28_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pc28_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pc28_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pc28_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pc28_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type GoldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url       string `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Origin    string `protobuf:"bytes,12,opt,name=origin,proto3" json:"origin,omitempty"`
	Cookie    string `protobuf:"bytes,13,opt,name=cookie,proto3" json:"cookie,omitempty"`
	UserAgent string `protobuf:"bytes,14,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Unix      string `protobuf:"bytes,31,opt,name=unix,proto3" json:"unix,omitempty"`
	KeyCode   string `protobuf:"bytes,32,opt,name=keyCode,proto3" json:"keyCode,omitempty"`
	PType     string `protobuf:"bytes,33,opt,name=pType,proto3" json:"pType,omitempty"`
	DeviceId  string `protobuf:"bytes,34,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	ChannelId string `protobuf:"bytes,35,opt,name=channelId,proto3" json:"channelId,omitempty"`
	UserId    string `protobuf:"bytes,36,opt,name=userId,proto3" json:"userId,omitempty"`
	Token     string `protobuf:"bytes,37,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GoldRequest) Reset() {
	*x = GoldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pc28_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoldRequest) ProtoMessage() {}

func (x *GoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pc28_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoldRequest.ProtoReflect.Descriptor instead.
func (*GoldRequest) Descriptor() ([]byte, []int) {
	return file_pc28_proto_rawDescGZIP(), []int{2}
}

func (x *GoldRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GoldRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *GoldRequest) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *GoldRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *GoldRequest) GetUnix() string {
	if x != nil {
		return x.Unix
	}
	return ""
}

func (x *GoldRequest) GetKeyCode() string {
	if x != nil {
		return x.KeyCode
	}
	return ""
}

func (x *GoldRequest) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *GoldRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GoldRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GoldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GoldRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GoldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gold int64 `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
}

func (x *GoldResponse) Reset() {
	*x = GoldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pc28_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoldResponse) ProtoMessage() {}

func (x *GoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pc28_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoldResponse.ProtoReflect.Descriptor instead.
func (*GoldResponse) Descriptor() ([]byte, []int) {
	return file_pc28_proto_rawDescGZIP(), []int{3}
}

func (x *GoldResponse) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type BettingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url       string          `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Origin    string          `protobuf:"bytes,12,opt,name=origin,proto3" json:"origin,omitempty"`
	Cookie    string          `protobuf:"bytes,13,opt,name=cookie,proto3" json:"cookie,omitempty"`
	UserAgent string          `protobuf:"bytes,14,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Issue     string          `protobuf:"bytes,21,opt,name=issue,proto3" json:"issue,omitempty"`
	Bets      map[int32]int32 `protobuf:"bytes,22,rep,name=bets,proto3" json:"bets,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Unix      string          `protobuf:"bytes,31,opt,name=unix,proto3" json:"unix,omitempty"`
	KeyCode   string          `protobuf:"bytes,32,opt,name=keyCode,proto3" json:"keyCode,omitempty"`
	PType     string          `protobuf:"bytes,33,opt,name=pType,proto3" json:"pType,omitempty"`
	DeviceId  string          `protobuf:"bytes,34,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	ChannelId string          `protobuf:"bytes,35,opt,name=channelId,proto3" json:"channelId,omitempty"`
	UserId    string          `protobuf:"bytes,36,opt,name=userId,proto3" json:"userId,omitempty"`
	Token     string          `protobuf:"bytes,37,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *BettingRequest) Reset() {
	*x = BettingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pc28_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingRequest) ProtoMessage() {}

func (x *BettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pc28_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingRequest.ProtoReflect.Descriptor instead.
func (*BettingRequest) Descriptor() ([]byte, []int) {
	return file_pc28_proto_rawDescGZIP(), []int{4}
}

func (x *BettingRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BettingRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *BettingRequest) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *BettingRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *BettingRequest) GetIssue() string {
	if x != nil {
		return x.Issue
	}
	return ""
}

func (x *BettingRequest) GetBets() map[int32]int32 {
	if x != nil {
		return x.Bets
	}
	return nil
}

func (x *BettingRequest) GetUnix() string {
	if x != nil {
		return x.Unix
	}
	return ""
}

func (x *BettingRequest) GetKeyCode() string {
	if x != nil {
		return x.KeyCode
	}
	return ""
}

func (x *BettingRequest) GetPType() string {
	if x != nil {
		return x.PType
	}
	return ""
}

func (x *BettingRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BettingRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *BettingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BettingRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type BettingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BettingResponse) Reset() {
	*x = BettingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pc28_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BettingResponse) ProtoMessage() {}

func (x *BettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pc28_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BettingResponse.ProtoReflect.Descriptor instead.
func (*BettingResponse) Descriptor() ([]byte, []int) {
	return file_pc28_proto_rawDescGZIP(), []int{5}
}

var File_pc28_proto protoreflect.FileDescriptor

var file_pc28_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x63, 0x32, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c,
	0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x99, 0x02, 0x0a,
	0x0b, 0x47, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x6e, 0x69, 0x78, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x78,
	0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x20, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x21, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x22, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x23, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x24, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x25, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x22, 0x0a, 0x0c, 0x47, 0x6f, 0x6c, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x22, 0xa0, 0x03, 0x0a,
	0x0e, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x62, 0x65, 0x74, 0x73, 0x18, 0x16, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x65, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x62, 0x65, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x78, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x78, 0x12, 0x18,
	0x0a, 0x07, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x20, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x21, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x22, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x23, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x24, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x25, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x37, 0x0a, 0x09, 0x42, 0x65, 0x74, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x11, 0x0a, 0x0f, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x48, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x40, 0x0a, 0x0b,
	0x47, 0x6f, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x47,
	0x6f, 0x6c, 0x64, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x6c, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x4c,
	0x0a, 0x0e, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3a, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pc28_proto_rawDescOnce sync.Once
	file_pc28_proto_rawDescData = file_pc28_proto_rawDesc
)

func file_pc28_proto_rawDescGZIP() []byte {
	file_pc28_proto_rawDescOnce.Do(func() {
		file_pc28_proto_rawDescData = protoimpl.X.CompressGZIP(file_pc28_proto_rawDescData)
	})
	return file_pc28_proto_rawDescData
}

var file_pc28_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pc28_proto_goTypes = []interface{}{
	(*SearchRequest)(nil),   // 0: proto.SearchRequest
	(*SearchResponse)(nil),  // 1: proto.SearchResponse
	(*GoldRequest)(nil),     // 2: proto.GoldRequest
	(*GoldResponse)(nil),    // 3: proto.GoldResponse
	(*BettingRequest)(nil),  // 4: proto.BettingRequest
	(*BettingResponse)(nil), // 5: proto.BettingResponse
	nil,                     // 6: proto.BettingRequest.BetsEntry
}
var file_pc28_proto_depIdxs = []int32{
	6, // 0: proto.BettingRequest.bets:type_name -> proto.BettingRequest.BetsEntry
	0, // 1: proto.SearchService.Search:input_type -> proto.SearchRequest
	2, // 2: proto.GoldService.Gold:input_type -> proto.GoldRequest
	4, // 3: proto.BettingService.Betting:input_type -> proto.BettingRequest
	1, // 4: proto.SearchService.Search:output_type -> proto.SearchResponse
	3, // 5: proto.GoldService.Gold:output_type -> proto.GoldResponse
	5, // 6: proto.BettingService.Betting:output_type -> proto.BettingResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pc28_proto_init() }
func file_pc28_proto_init() {
	if File_pc28_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pc28_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pc28_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pc28_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pc28_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pc28_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BettingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pc28_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BettingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pc28_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pc28_proto_goTypes,
		DependencyIndexes: file_pc28_proto_depIdxs,
		MessageInfos:      file_pc28_proto_msgTypes,
	}.Build()
	File_pc28_proto = out.File
	file_pc28_proto_rawDesc = nil
	file_pc28_proto_goTypes = nil
	file_pc28_proto_depIdxs = nil
}
